package:
  name: spinsfast
  version: {{ environ.get('package_version', '104.1') }}

source:
  git_url: https://github.com/moble/spinsfast.git

# build:
#   # script: python setup.py install
#   # script: python setup.py bdist_wheel

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python {{ python }}
    - numpy
    - fftw

  run:
    - python {{ python }}
    - numpy
    - fftw

about:
  home: 'http://astrophysics.physics.fsu.edu/~huffenbe/research/spinsfast/index.html'
  license: GPL
  summary: 'Fast and exact spin-s spherical-harmonic transforms'
