name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

    - name: Install miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        python-version: '3.7'
        channels: conda-forge

    - name: Install conda packages and build wheel
      shell: bash -l {0}
      run: |
        conda update -n base -c defaults conda
        conda install numpy fftw pip

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.5.5
      shell: bash -l {0}

    - name: Install Visual C++ for Python 2.7
      if: runner.os == 'Windows'
      run: |
        choco install vcpython27 -f -y
      shell: bash -l {0}

    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      shell: bash -l {0}

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
