name: build wheels for macos

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        architecture: [x64]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: install conda packages
      shell: bash -l {0}
      run: |
        conda install numpy fftw pip
        export LIBRARY_PATH="${CONDA_PREFIX}"/lib
        export C_INCLUDE_PATH="${CONDA_PREFIX}"/include
    - name: build wheel
      shell: bash -l {0}
      run: |
        pip install --upgrade pip wheel auditwheel
        pip install -r ./python/dev-requirements.txt
        python setup.py bdist_wheel
    - name: upload wheel
      uses: actions/upload-artifact@v1
      with:
        name: dist_${{ matrix.os }}_${{ matrix.architecture }}_${{ matrix.python-version }}
        path: dist
    - name: Publish to PyPI
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USER }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      shell: bash -l {0}
      run: |
        pip install twine
        python -m twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
