name: build wheels for linux

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Install conda packages
      shell: bash -l {0}
      run: |
        conda update -n base -c defaults conda
        conda install numpy fftw pip
        export LIBRARY_PATH="${CONDA_PREFIX}"/lib
        export C_INCLUDE_PATH="${CONDA_PREFIX}"/include
    - uses: ./.github/workflows/actions/manylinux1_x86_64/
    - uses: ./.github/workflows/actions/manylinux1_i686/
    - name: Copy manylinux wheels
      run: |
        mkdir dist
        cp wheelhouse/spinsfast*-manylinux1*.whl dist/
    - name: Upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
    - name: Publish to PyPI
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        python -m twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
      shell: bash -l {0}
