name: build wheels for linux

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/manylinux1_x86_64/
    - uses: ./.github/workflows/actions/manylinux1_i686/
    - name: copy manylinux wheels
      run: |
        mkdir dist
        cp wheelhouse/spinsfast*-manylinux1*.whl dist/
    - name: upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
    - name: Publish to PyPI
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USER }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        python -m twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
